# Generated by Django 3.2.4 on 2021-06-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('open_timestamp', models.DateTimeField()),
                ('closed_timestamp', models.DateTimeField()),
                ('issuetext', models.CharField(max_length=1000)),
                ('ticket_state', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='registry.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('effective_date', models.DateField(blank=True)),
                ('effective_time', models.TimeField(blank=True)),
                ('activity_state', models.IntegerField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='registry.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='help_desk.ticket')),
            ],
        ),
    ]
